name = "aws4_request"
version = "0.1.0"
gleam = ">= 0.32.0"
description = "An AWS Signature Version 4 client implementation, used for S3 auth, etc"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "aws4_request" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_http = "~> 3.5"
gleam_crypto = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 1.0"
